### PR TITLE
added german translations (values-de/strings.xml)

### PR DESCRIPTION
**Pull request by D-E-N**
I translated the used strings of values/strings.xml to german.

PS: What is ment with the menu item "long tasks" in the main menu between "next tasks" and "all tasks"?

### CODE REVIEW

**Comment by svijee** [comment]
Hi,

I named the menu items after the command. So "task next" in the menu has the same output like "$ task next" with original taskwarrior. Same with task long and task all. So it's better to not translate them.

I've had a look on the other translations and I think, it's better to _not_ translate the word "task" into "Aufgabe". It's more a personal opinion, because taskwarrior users are used to call it "task".

**Comment by D-E-N** [comment]
Ok, this sounds logical :)

**Comment by D-E-N** [comment]
One question, why is there the menu "task long", it only gives more details (in the original), but in the app the details are always the some, right? So i think it's unnecessary.

**Comment by svijee** [comment]
Not completely unnecessary. "task long" is sorted after  the due date. "task next" uses the "urgency"-coefficent to sort the tasks. Later I want to extend the details of "task long".

**Comment by D-E-N** [comment]
ok. Is it possible to make a line, or something else between the three task commands and the projectlist?

**Pull request merged**
